name       : kitematic
version    : 0.13.1
release    : 3
source     :
    - https://github.com/docker/kitematic/archive/v0.13.1.tar.gz : 88d3d46b6fb400ad8c366e940e410d5b81b52215b39a1290ff1f2ff4f2b55ea5
license    : Apache 2.0
networking : yes
component  : programming.tools
summary    : Visual Docker Container Management
description: |
    Kitematic is a simple application for managing Docker containers on Mac, Linux and Windows.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xtst)
    - cups-devel
    - git
    - nodejs
rundeps    :
    - docker
setup      : |
    npm install
build      : |
    ./node_modules/.bin/grunt babel less copy:dev shell:linux_npm electron-packager:build
install    : |
    install -d $installdir/usr/bin
    install -d $installdir/usr/share
    cp -Rv dist/Kitematic-linux-x64 $installdir/usr/share/kitematic
    install -Dm00644 $pkgfiles/kitematic.desktop $installdir/usr/share/applications/kitematic.desktop
    install -Dm00644 $pkgfiles/kitematic.svg $installdir/usr/share/icons/hicolor/scalable/apps/kitematic.svg
    ln -s /usr/share/kitematic/Kitematic $installdir/usr/bin/kitematic
